### ISSUE TITLE
Fatal signal when compress photo on armeabi-v7a

### ISSUE THREAD

**Issue by KhanTF** [Sunzxyong/Tiny#71]
libtiny.so: unused DT entry: type 0x6ffffffe arg 0x2f78
libtiny.so: unused DT entry: type 0x6fffffff arg 0x1
eglMakeCurrent: 0xa544afa0: ver 2 0
Bitmap format : RGBA_8888, width:1280, height:960 
Fatal signal 4 (SIGILL), code 1, fault addr 0xa3e3f918 in tid 7116 (pool-1-thread-1)

val options = Tiny.FileCompressOptions() 
val result = Tiny.getInstance()
            .source(photo)
            .asFile()
            .withOptions(options)
            .compressSync()
if (result.success) {
            File(result.outfile)
} else {
            photo
}

**Comment by Sunzxyong** [comment]
@KhanTF Please provide the mobile os version and model

**Comment by Sunzxyong** [comment]
@KhanTF Please also provide full log info, like WARNING: linker: ..

**Comment by ciuciuciu** [comment]
@Sunzxyong, I had same error and here is log

java.lang.UnsatisfiedLinkError: No implementation found for boolean com.imagelib.libjpegturbo.JpegTurboCompressor.nativeCompress(android.graphics.Bitmap, java.lang.String, int, boolean) (tried Java_com_imagelib_libjpegturbo_JpegTurboCompressor_nativeCompress and Java_com_imagelib_libjpegturbo_JpegTurboCompressor_nativeCompress__Landroid_graphics_Bitmap_2Ljava_lang_String_2IZ)
    at com.imagelib.libjpegturbo.JpegTurboCompressor.nativeCompress(JpegTurboCompressor.java)
    at com.imagelib.libjpegturbo.JpegTurboCompressor.compress(JpegTurboCompressor.java:8)
    at com.imagelib.tiny.core.FileCompressor.compress(FileCompressor.java:124)
    at com.imagelib.tiny.core.FileCompressor.compress(FileCompressor.java:67)
    at com.imagelib.tiny.callable.FileCompressCallableTasks$UriAsFileCallable.call(FileCompressCallableTasks.java:98)
    at com.imagelib.tiny.core.FileCompressEngine.implSync(FileCompressEngine.java:82)
    at com.imagelib.tiny.core.FileCompressEngine.compressSync(FileCompressEngine.java:38)
    at vn.mobileapp.imagemodule.ImageCompressorModule.myCompressImage(ImageCompressorModule.java:67)
    at vn.mobileapp.imagemodule.ImageCompressorModule.compressImage(ImageCompressorModule.java:36)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:148)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
    at java.lang.Thread.run(Thread.java:818)

java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:148)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
    at java.lang.Thread.run(Thread.java:818)

java.lang.RuntimeException: Could not invoke ImageCompressorBridge.compressImage
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:148)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
    at java.lang.Thread.run(Thread.java:818)
